// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njcyzjnnimdaxbocfewc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qY3l6am5uaW1kYXhib2NmZXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjE0OTMsImV4cCI6MjA3MDA5NzQ5M30.hw-H2abuhsHr6BpVdG7sCH5qMC5_SD4cLiJIJ-G1hNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});